version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - cd Idea-Archive-Server
      - chmod +x ./gradlew
      - ./gradlew clean build --exclude-task test
artifacts:
  files:
    - Idea-Archive-Server/build/libs/*.jar
    - Idea-Archive-Server/scripts/**
    - Idea-Archive-Server/appspec.yml
  discard-paths: yes


  